#include "LibNcurses.hpp"

namespace arcade
{
  // Mapping Ncurses Mouse Button with MouseKey enum
  std::map<int, MouseKey> LibNcurses::m_mouse_keys = {
      {1, M_LEFT_CLICK}, {2, M_MIDDLE_CLICK}, {3, M_RIGHT_CLICK},
      {4, M_SCROLL_UP},  {5, M_SCROLL_DOWN},  {6, M_BT0},
      {7, M_BT1}};

  // Mapping Ncurses keyboard map
  std::map<int, KeyboardKey> LibNcurses::m_kb_keys = {
      {'0', KB_0},
      {'1', KB_1},
      {'2', KB_2},
      {'3', KB_3},
      {'4', KB_4},
      {'5', KB_5},
      {'6', KB_6},
      {'7', KB_7},
      {'8', KB_8},
      {'9', KB_9},
      {'a', KB_A},
      {'b', KB_B},
      {'c', KB_C},
      {'d', KB_D},
      {'e', KB_E},
      {'f', KB_F},
      {'g', KB_G},
      {'h', KB_H},
      {'i', KB_I},
      {'j', KB_J},
      {'k', KB_K},
      {'l', KB_L},
      {'m', KB_M},
      {'n', KB_N},
      {'o', KB_O},
      {'p', KB_P},
      {'q', KB_Q},
      {'r', KB_R},
      {'s', KB_S},
      {'t', KB_T},
      {'u', KB_U},
      {'v', KB_V},
      {'w', KB_W},
      {'x', KB_X},
      {'y', KB_Y},
      {'z', KB_Z},
      {'\\', KB_BACKSLASH},
      {KEY_BACKSPACE, KB_BACKSPACE},
      {',', KB_COMMA},
      {KEY_DOWN, KB_ARROW_DOWN},
      {'=', KB_EQUALS},
      {27, KB_ESCAPE},
      {KEY_HOME, KB_HOME},
      {'0', KB_0},
      {'1', KB_1},
      {'2', KB_2},
      {'3', KB_3},
      {'4', KB_4},
      {'5', KB_5},
      {'6', KB_6},
      {'7', KB_7},
      {'8', KB_8},
      {'9', KB_9},
      {'-', KB_MINUS},
      {'*', KB_ASTERISK},
      {'%', KB_PERCENT},
      {'.', KB_DOT},
      {'+', KB_PLUS},
      {'-', KB_MINUS},
      {KEY_LEFT, KB_ARROW_LEFT},
      {'[', KB_LEFTBRACKET},
      {'-', KB_MINUS},
      {'.', KB_DOT},
      {KEY_RIGHT, KB_ARROW_RIGHT},
      {']', KB_RIGHTBRACKET},
      {';', KB_SEMICOLON},
      {'/', KB_SLASH},
      {' ', KB_SPACE},
      {KEY_UP, KB_ARROW_UP},
      {'&', KB_AMPERSAND},
      {'*', KB_ASTERISK},
      {'@', KB_ATSYMBOL},
      {'^', KB_CIRCUMFLEX},
      {':', KB_COLON},
      {'$', KB_DOLLAR},
      {'!', KB_EXCLAMATION},
      {'>', KB_SUPERIOR},
      {'#', KB_HASHTAG},
      {'(', KB_LEFTPAREN},
      {'<', KB_INFERIOR},
      {'%', KB_PERCENT},
      {'+', KB_PLUS},
      {'?', KB_QUESTION},
      {'"', KB_DOUBLEQUOTE},
      {')', KB_RIGHTPAREN},
      {'_', KB_UNDERSCORE},
      {'\n', KB_ENTER}};
}
