#include "LibNcurses.hpp"

namespace arcade
{
  // Mapping Ncurses Mouse Button with MouseKey enum
  std::map<int, MouseKey> LibNcurses::m_mouse_keys =
    {
      { 1, M_LEFT_CLICK },
      { 2, M_MIDDLE_CLICK },
      { 3, M_RIGHT_CLICK },
      { 4, M_SCROLL_UP },
      { 5, M_SCROLL_DOWN },
      { 6, M_BT0 },
      { 7, M_BT1 }
    };

  // Mapping Ncurses keyboard map
  std::map<int, KeyboardKey> LibNcurses::m_kb_keys =
    {
      { '0', KB_0 },
      { '1', KB_1 },
      { '2', KB_2 },
      { '3', KB_3 },
      { '4', KB_4 },
      { '5', KB_5 },
      { '6', KB_6 },
      { '7', KB_7 },
      { '8', KB_8 },
      { '9', KB_9 },
      { 'a', KB_A },
      { 'b', KB_B },
      { 'c', KB_C },
      { 'd', KB_D },
      { 'e', KB_E },
      { 'f', KB_F },
      { 'g', KB_G },
      { 'h', KB_H },
      { 'i', KB_I },
      { 'j', KB_J },
      { 'k', KB_K },
      { 'l', KB_L },
      { 'm', KB_M },
      { 'n', KB_N },
      { 'o', KB_O },
      { 'p', KB_P },
      { 'q', KB_Q },
      { 'r', KB_R },
      { 's', KB_S },
      { 't', KB_T },
      { 'u', KB_U },
      { 'v', KB_V },
      { 'w', KB_W },
      { 'x', KB_X },
      { 'y', KB_Y },
      { 'z', KB_Z },
      { '\\', KB_BACKSLASH },
      { KEY_BACKSPACE, KB_BACKSPACE },
      //{ , KB_CAPSLOCK },
      { ',', KB_COMMA },
      //{ NCURSES_KEY_DELETE, KB_DELETE },
      { KEY_DOWN, KB_ARROW_DOWN },
      //{ , KB_END },
      { '=', KB_EQUALS },
      { 27, KB_ESCAPE },
      //{ NCURSES_KEY_F1, KB_FN1 },
      //{ NCURSES_KEY_F2, KB_FN2 },
      //{ NCURSES_KEY_F3, KB_FN3 },
      //{ NCURSES_KEY_F4, KB_FN4 },
      //{ NCURSES_KEY_F5, KB_FN5 },
      //{ NCURSES_KEY_F6, KB_FN6 },
      //{ NCURSES_KEY_F7, KB_FN7 },
      //{ NCURSES_KEY_F8, KB_FN8 },
      //{ NCURSES_KEY_F9, KB_FN9 },
      //{ NCURSES_KEY_F10, KB_FN10 },
      //{ NCURSES_KEY_F11, KB_FN11 },
      //{ NCURSES_KEY_F12, KB_FN12 },
      { KEY_HOME, KB_HOME },
      { '0', KB_0 },
      { '1', KB_1 },
      { '2', KB_2 },
      { '3', KB_3 },
      { '4', KB_4 },
      { '5', KB_5 },
      { '6', KB_6 },
      { '7', KB_7 },
      { '8', KB_8 },
      { '9', KB_9 },
      { '-', KB_MINUS },
      { '*', KB_ASTERISK },
      { '%', KB_PERCENT },
      { '.', KB_DOT },
      { '+', KB_PLUS },
      { '-', KB_MINUS },
      //{ , KB_LALT },
      //{ , KB_LCTRL },
      { KEY_LEFT, KB_ARROW_LEFT },
      { '[', KB_LEFTBRACKET },
      //{ , KB_LSHIFT },
      { '-', KB_MINUS },
      //{ NCURSES_KEY_PAGEDOWN, KB_PAGEDOWN },
      //{ NCURSES_KEY_PAGEUP, KB_PAGEUP },
      { '.', KB_DOT },
      //{ , KB_RALT },
      //{ , KB_RCTRL },
      { KEY_RIGHT, KB_ARROW_RIGHT },
      { ']', KB_RIGHTBRACKET },
      //{ , KB_RSHIFT },
      { ';', KB_SEMICOLON },
      { '/', KB_SLASH },
      { ' ', KB_SPACE },
      //{ NCURSES_KEY_TAB, KB_TAB },
      { KEY_UP, KB_ARROW_UP },
      { '&', KB_AMPERSAND },
      { '*', KB_ASTERISK },
      { '@', KB_ATSYMBOL },
      { '^', KB_CIRCUMFLEX },
      { ':', KB_COLON },
      { '$', KB_DOLLAR },
      { '!', KB_EXCLAMATION },
      { '>', KB_SUPERIOR },
      { '#', KB_HASHTAG },
      { '(', KB_LEFTPAREN },
      { '<', KB_INFERIOR },
      { '%', KB_PERCENT },
      { '+', KB_PLUS },
      { '?', KB_QUESTION },
      { '"', KB_DOUBLEQUOTE },
      { ')', KB_RIGHTPAREN },
      { '_', KB_UNDERSCORE },
      { '\n', KB_ENTER }
    };
}
