#include "LibAllegro5.hpp"

namespace arcade
{
  // Mapping SFML Mouse Button with MouseKey enum
  std::map<int, MouseKey> LibAllegro5::m_mouse_keys =
    {
      { ' ', M_LEFT_CLICK },
      { ' ', M_MIDDLE_CLICK },
      { ' ', M_RIGHT_CLICK },
      { ' ', M_BT0 },
      { ' ', M_BT1 }
    };

  std::map<int, KeyboardKey> LibAllegro5::m_kb_keys =
    {
      { ALLEGRO_KEY_0, KB_0 },
      { ALLEGRO_KEY_1, KB_1 },
      { ALLEGRO_KEY_2, KB_2 },
      { ALLEGRO_KEY_3, KB_3 },
      { ALLEGRO_KEY_4, KB_4 },
      { ALLEGRO_KEY_5, KB_5 },
      { ALLEGRO_KEY_6, KB_6 },
      { ALLEGRO_KEY_7, KB_7 },
      { ALLEGRO_KEY_8, KB_8 },
      { ALLEGRO_KEY_9, KB_9 },
      { ALLEGRO_KEY_A, KB_A },
      { ALLEGRO_KEY_B, KB_B },
      { ALLEGRO_KEY_C, KB_C },
      { ALLEGRO_KEY_D, KB_D },
      { ALLEGRO_KEY_E, KB_E },
      { ALLEGRO_KEY_F, KB_F },
      { ALLEGRO_KEY_G, KB_G },
      { ALLEGRO_KEY_H, KB_H },
      { ALLEGRO_KEY_I, KB_I },
      { ALLEGRO_KEY_J, KB_J },
      { ALLEGRO_KEY_K, KB_K },
      { ALLEGRO_KEY_L, KB_L },
      { ALLEGRO_KEY_M, KB_M },
      { ALLEGRO_KEY_N, KB_N },
      { ALLEGRO_KEY_O, KB_O },
      { ALLEGRO_KEY_P, KB_P },
      { ALLEGRO_KEY_Q, KB_Q },
      { ALLEGRO_KEY_R, KB_R },
      { ALLEGRO_KEY_S, KB_S },
      { ALLEGRO_KEY_T, KB_T },
      { ALLEGRO_KEY_U, KB_U },
      { ALLEGRO_KEY_V, KB_V },
      { ALLEGRO_KEY_W, KB_W },
      { ALLEGRO_KEY_X, KB_X },
      { ALLEGRO_KEY_Y, KB_Y },
      { ALLEGRO_KEY_Z, KB_Z },
      //{ allegro_sys::keycodesBackSlash, KB_BACKSLASH },
      //{ allegro_sys::keycodesBackSpace, KB_BACKSPACE },
      //{ allegro_sys::keycodes, KB_CAPSLOCK },
      //{ allegro_sys::keycodesComma, KB_COMMA },
      //{ allegro_sys::keycodesDelete, KB_DELETE },
      //{ allegro_sys::keycodesDown, KB_ARROW_DOWN },
      //{ allegro_sys::keycodesEnd, KB_END },
      //{ allegro_sys::keycodesEqual, KB_EQUALS },
      { ALLEGRO_KEY_ESCAPE, KB_ESCAPE },
      //{ allegro_sys::keycodesF1, KB_FN1 },
      //{ allegro_sys::keycodesF2, KB_FN2 },
      //{ allegro_sys::keycodesF3, KB_FN3 },
      //{ allegro_sys::keycodesF4, KB_FN4 },
      //{ allegro_sys::keycodesF5, KB_FN5 },
      //{ allegro_sys::keycodesF6, KB_FN6 },
      //{ allegro_sys::keycodesF7, KB_FN7 },
      //{ allegro_sys::keycodesF8, KB_FN8 },
      //{ allegro_sys::keycodesF9, KB_FN9 },
      //{ allegro_sys::keycodesF10, KB_FN10 },
      //{ allegro_sys::keycodesF11, KB_FN11 },
      //{ allegro_sys::keycodesF12, KB_FN12 },
      //{ allegro_sys::keycodesHome, KB_HOME },
      //{ allegro_sys::keycodesNumpad0, KB_0 },
      //{ allegro_sys::keycodesNumpad1, KB_1 },
      //{ allegro_sys::keycodesNumpad2, KB_2 },
      //{ allegro_sys::keycodesNumpad3, KB_3 },
      //{ allegro_sys::keycodesNumpad4, KB_4 },
      //{ allegro_sys::keycodesNumpad5, KB_5 },
      //{ allegro_sys::keycodesNumpad6, KB_6 },
      //{ allegro_sys::keycodesNumpad7, KB_7 },
      //{ allegro_sys::keycodesNumpad8, KB_8 },
      //{ allegro_sys::keycodesNumpad9, KB_9 },
      //{ allegro_sys::keycodesSubtract, KB_MINUS },
      //{ allegro_sys::keycodesMultiply, KB_ASTERISK },
      //{ SDLK_KP_PERCENT, KB_PERCENT },
      //{ allegro_sys::keycodesPeriod, KB_DOT },
      //{ allegro_sys::keycodesAdd, KB_PLUS },
      //{ allegro_sys::keycodesDash, KB_MINUS },
      //{ allegro_sys::keycodesLAlt, KB_LALT },
      //{ allegro_sys::keycodesLControl, KB_LCTRL },
      //{ allegro_sys::keycodesLeft, KB_ARROW_LEFT },
      //{ allegro_sys::keycodesLBracket, KB_LEFTBRACKET },
      //{ allegro_sys::keycodesLShift, KB_LSHIFT },
      //{ allegro_sys::keycodesDash, KB_MINUS },
      //{ allegro_sys::keycodesPageDown, KB_PAGEDOWN },
      //{ allegro_sys::keycodesPageUp, KB_PAGEUP },
      //{ allegro_sys::keycodesPeriod, KB_DOT },
      //{ allegro_sys::keycodesRAlt, KB_RALT },
      //{ allegro_sys::keycodesRControl, KB_RCTRL },
      //{ allegro_sys::keycodesRight, KB_ARROW_RIGHT },
      //{ allegro_sys::keycodesRBracket, KB_RIGHTBRACKET },
      //{ allegro_sys::keycodesRShift, KB_RSHIFT },
      //{ allegro_sys::keycodesSemiColon, KB_SEMICOLON },
      //{ allegro_sys::keycodesDivide, KB_SLASH },
      //{ allegro_sys::keycodesSpace, KB_SPACE },
      //{ allegro_sys::keycodesTab, KB_TAB },
      //{ allegro_sys::keycodesUp, KB_ARROW_UP },
      //{ SDLK_AMPERSAND, KB_AMPERSAND },
      //{ allegro_sys::keycodesMultiply, KB_ASTERISK },
      //{ SDLK_AT, KB_ATSYMBOL },
      //{ SDLK_CARET, KB_CIRCUMFLEX },
      //{ SDLK_COLON, KB_COLON },
      //{ SDLK_DOLLAR, KB_DOLLAR },
      //{ SDLK_EXCLAIM, KB_EXCLAMATION },
      //{ SDLK_GREATER, KB_SUPERIOR },
      //{ SDLK_HASH, KB_HASHTAG },
      //{ SDLK_LEFTPAREN, KB_LEFTPAREN },
      //{ SDLK_LESS, KB_INFERIOR },OB
      //{ SDLK_PERCENT, KB_PERCENT },
      //{ ' ', KB_PLUS },
      //{ ' ', KB_ENTER}
      //{ SDLK_QUESTION, KB_QUESTION },
      //{ SDLK_QUOTEDBL, KB_DOUBLEQUOTE },
      //{ SDLK_RIGHTPAREN, KB_RIGHTPAREN },
      //{ SDLK_UNDERSCORE, KB_UNDERSCORE }
    };
}
