#include "LibAllegro5.hpp"

namespace arcade
{
  // Mapping SFML Mouse Button with MouseKey enum
  std::map<int, MouseKey> LibAllegro5::m_mouse_keys = {{' ', M_LEFT_CLICK},
                                                       {' ', M_MIDDLE_CLICK},
                                                       {' ', M_RIGHT_CLICK},
                                                       {' ', M_BT0},
                                                       {' ', M_BT1}};

  std::map<int, KeyboardKey> LibAllegro5::m_kb_keys = {
      {ALLEGRO_KEY_0, KB_0},
      {ALLEGRO_KEY_1, KB_1},
      {ALLEGRO_KEY_2, KB_2},
      {ALLEGRO_KEY_3, KB_3},
      {ALLEGRO_KEY_4, KB_4},
      {ALLEGRO_KEY_5, KB_5},
      {ALLEGRO_KEY_6, KB_6},
      {ALLEGRO_KEY_7, KB_7},
      {ALLEGRO_KEY_8, KB_8},
      {ALLEGRO_KEY_9, KB_9},
      {ALLEGRO_KEY_A, KB_A},
      {ALLEGRO_KEY_B, KB_B},
      {ALLEGRO_KEY_C, KB_C},
      {ALLEGRO_KEY_D, KB_D},
      {ALLEGRO_KEY_E, KB_E},
      {ALLEGRO_KEY_F, KB_F},
      {ALLEGRO_KEY_G, KB_G},
      {ALLEGRO_KEY_H, KB_H},
      {ALLEGRO_KEY_I, KB_I},
      {ALLEGRO_KEY_J, KB_J},
      {ALLEGRO_KEY_K, KB_K},
      {ALLEGRO_KEY_L, KB_L},
      {ALLEGRO_KEY_M, KB_M},
      {ALLEGRO_KEY_N, KB_N},
      {ALLEGRO_KEY_O, KB_O},
      {ALLEGRO_KEY_P, KB_P},
      {ALLEGRO_KEY_Q, KB_Q},
      {ALLEGRO_KEY_R, KB_R},
      {ALLEGRO_KEY_S, KB_S},
      {ALLEGRO_KEY_T, KB_T},
      {ALLEGRO_KEY_U, KB_U},
      {ALLEGRO_KEY_V, KB_V},
      {ALLEGRO_KEY_W, KB_W},
      {ALLEGRO_KEY_X, KB_X},
      {ALLEGRO_KEY_Y, KB_Y},
      {ALLEGRO_KEY_Z, KB_Z},
      {ALLEGRO_KEY_BACKSLASH, KB_BACKSLASH},
      {ALLEGRO_KEY_BACKSPACE, KB_BACKSPACE},
      {ALLEGRO_KEY_CAPSLOCK, KB_CAPSLOCK},
      {ALLEGRO_KEY_COMMA, KB_COMMA},
      {ALLEGRO_KEY_DELETE, KB_DELETE},
      {ALLEGRO_KEY_DOWN, KB_ARROW_DOWN},
      {ALLEGRO_KEY_END, KB_END},
      {ALLEGRO_KEY_EQUALS, KB_EQUALS},
      {ALLEGRO_KEY_ESCAPE, KB_ESCAPE},
      {ALLEGRO_KEY_F1, KB_FN1},
      {ALLEGRO_KEY_F2, KB_FN2},
      {ALLEGRO_KEY_F3, KB_FN3},
      {ALLEGRO_KEY_F4, KB_FN4},
      {ALLEGRO_KEY_F5, KB_FN5},
      {ALLEGRO_KEY_F6, KB_FN6},
      {ALLEGRO_KEY_F7, KB_FN7},
      {ALLEGRO_KEY_F8, KB_FN8},
      {ALLEGRO_KEY_F9, KB_FN9},
      {ALLEGRO_KEY_F10, KB_FN10},
      {ALLEGRO_KEY_F11, KB_FN11},
      {ALLEGRO_KEY_F12, KB_FN12},
      {ALLEGRO_KEY_HOME, KB_HOME},
      {ALLEGRO_KEY_PAD_0, KB_0},
      {ALLEGRO_KEY_PAD_1, KB_1},
      {ALLEGRO_KEY_PAD_2, KB_2},
      {ALLEGRO_KEY_PAD_3, KB_3},
      {ALLEGRO_KEY_PAD_4, KB_4},
      {ALLEGRO_KEY_PAD_5, KB_5},
      {ALLEGRO_KEY_PAD_6, KB_6},
      {ALLEGRO_KEY_PAD_7, KB_7},
      {ALLEGRO_KEY_PAD_8, KB_8},
      {ALLEGRO_KEY_PAD_9, KB_9},
      {ALLEGRO_KEY_MINUS, KB_MINUS},
      {ALLEGRO_KEY_MINUS, KB_MINUS},
      {ALLEGRO_KEY_ALT, KB_LALT},
      {ALLEGRO_KEY_LCTRL, KB_LCTRL},
      {ALLEGRO_KEY_LEFT, KB_ARROW_LEFT},
      {ALLEGRO_KEY_LSHIFT, KB_LSHIFT},
      {ALLEGRO_KEY_ALTGR, KB_RALT},
      {ALLEGRO_KEY_RCTRL, KB_RCTRL},
      {ALLEGRO_KEY_RIGHT, KB_ARROW_RIGHT},
      {ALLEGRO_KEY_RSHIFT, KB_RSHIFT},
      {ALLEGRO_KEY_SEMICOLON, KB_SEMICOLON},
      {ALLEGRO_KEY_SLASH, KB_SLASH},
      {ALLEGRO_KEY_SPACE, KB_SPACE},
      {ALLEGRO_KEY_TAB, KB_TAB},
      {ALLEGRO_KEY_UP, KB_ARROW_UP},
      {ALLEGRO_KEY_AT, KB_ATSYMBOL},
      {ALLEGRO_KEY_CIRCUMFLEX, KB_CIRCUMFLEX},
      {ALLEGRO_KEY_ENTER, KB_ENTER}};
}
