#include "Libcaca.hpp"

namespace arcade
{
  // Mapping caca Mouse Button with MouseKey enum
  std::map<int, MouseKey> Libcaca::m_mouse_keys = {
      {1, M_LEFT_CLICK}, {2, M_MIDDLE_CLICK}, {3, M_RIGHT_CLICK},
      {4, M_SCROLL_UP},  {5, M_SCROLL_DOWN},  {6, M_BT0},
      {7, M_BT1}};

  // Mapping caca keyboard map
  std::map<int, KeyboardKey> Libcaca::m_kb_keys = {
      {'0', KB_0},
      {'1', KB_1},
      {'2', KB_2},
      {'3', KB_3},
      {'4', KB_4},
      {'5', KB_5},
      {'6', KB_6},
      {'7', KB_7},
      {'8', KB_8},
      {'9', KB_9},
      {'a', KB_A},
      {'b', KB_B},
      {'c', KB_C},
      {'d', KB_D},
      {'e', KB_E},
      {'f', KB_F},
      {'g', KB_G},
      {'h', KB_H},
      {'i', KB_I},
      {'j', KB_J},
      {'k', KB_K},
      {'l', KB_L},
      {'m', KB_M},
      {'n', KB_N},
      {'o', KB_O},
      {'p', KB_P},
      {'q', KB_Q},
      {'r', KB_R},
      {'s', KB_S},
      {'t', KB_T},
      {'u', KB_U},
      {'v', KB_V},
      {'w', KB_W},
      {'x', KB_X},
      {'y', KB_Y},
      {'z', KB_Z},
      {'\\', KB_BACKSLASH},
      {CACA_KEY_BACKSPACE, KB_BACKSPACE},
      {',', KB_COMMA},
      {CACA_KEY_DELETE, KB_DELETE},
      {CACA_KEY_DOWN, KB_ARROW_DOWN},
      {'=', KB_EQUALS},
      {CACA_KEY_ESCAPE, KB_ESCAPE},
      {CACA_KEY_F1, KB_FN1},
      {CACA_KEY_F2, KB_FN2},
      {CACA_KEY_F3, KB_FN3},
      {CACA_KEY_F4, KB_FN4},
      {CACA_KEY_F5, KB_FN5},
      {CACA_KEY_F6, KB_FN6},
      {CACA_KEY_F7, KB_FN7},
      {CACA_KEY_F8, KB_FN8},
      {CACA_KEY_F9, KB_FN9},
      {CACA_KEY_F10, KB_FN10},
      {CACA_KEY_F11, KB_FN11},
      {CACA_KEY_F12, KB_FN12},
      {CACA_KEY_HOME, KB_HOME},
      {'0', KB_0},
      {'1', KB_1},
      {'2', KB_2},
      {'3', KB_3},
      {'4', KB_4},
      {'5', KB_5},
      {'6', KB_6},
      {'7', KB_7},
      {'8', KB_8},
      {'9', KB_9},
      {'-', KB_MINUS},
      {'*', KB_ASTERISK},
      {'%', KB_PERCENT},
      {'.', KB_DOT},
      {'+', KB_PLUS},
      {'-', KB_MINUS},
      {CACA_KEY_LEFT, KB_ARROW_LEFT},
      {'[', KB_LEFTBRACKET},
      {'-', KB_MINUS},
      {CACA_KEY_PAGEDOWN, KB_PAGEDOWN},
      {CACA_KEY_PAGEUP, KB_PAGEUP},
      {'.', KB_DOT},
      {CACA_KEY_RIGHT, KB_ARROW_RIGHT},
      {']', KB_RIGHTBRACKET},
      {';', KB_SEMICOLON},
      {'/', KB_SLASH},
      {' ', KB_SPACE},
      {CACA_KEY_TAB, KB_TAB},
      {CACA_KEY_UP, KB_ARROW_UP},
      {'&', KB_AMPERSAND},
      {'*', KB_ASTERISK},
      {'@', KB_ATSYMBOL},
      {'^', KB_CIRCUMFLEX},
      {':', KB_COLON},
      {'$', KB_DOLLAR},
      {'!', KB_EXCLAMATION},
      {'>', KB_SUPERIOR},
      {'#', KB_HASHTAG},
      {'(', KB_LEFTPAREN},
      {'<', KB_INFERIOR},
      {'%', KB_PERCENT},
      {'+', KB_PLUS},
      {'?', KB_QUESTION},
      {'"', KB_DOUBLEQUOTE},
      {')', KB_RIGHTPAREN},
      {'_', KB_UNDERSCORE},
      {CACA_KEY_RETURN, KB_ENTER}};
}
